version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: battleboats_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: battleboats
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - battleboats-network

volumes:
  db_data:

networks:
  battleboats-network:
    driver: bridge